export const daftarProduk = {
  data: [
    {
      id: 1,
      nama_produk: 'cleanser',
      merk: 'SK-II',
      harga: 'Rp350.000',
      stok: 5,
    },
    {
      id: 2,
      nama_produk: 'cleanser',
      merk: 'SK-II',
      harga: 'Rp350.000',
      stok: 5,
    },
    {
      id: 3,
      nama_produk: 'cleanser',
      merk: 'SK-II',
      harga: 'Rp350.000',
      stok: 5,
    },
    {
      id: 4,
      nama_produk: 'cleanser',
      merk: 'SK-II',
      harga: 'Rp350.000',
      stok: 5,
    },
    {
      id: 5,
      nama_produk: 'cleanser',
      merk: 'SK-II',
      harga: 'Rp350.000',
      stok: 5,
    },
    {
      id: 6,
      nama_produk: 'cleanser',
      merk: 'SK-II',
      harga: 'Rp350.000',
      stok: 5,
    },
    {
      id: 7,
      nama_produk: 'cleanser',
      merk: 'SK-II',
      harga: 'Rp350.000',
      stok: 5,
    },
    {
      id: 8,
      nama_produk: 'cleanser',
      merk: 'SK-II',
      harga: 'Rp350.000',
      stok: 5,
    },
    {
      id: 9,
      nama_produk: 'cleanser',
      merk: 'SK-II',
      harga: 'Rp350.000',
      stok: 5,
    },
    {
      id: 10,
      nama_produk: 'cleanser',
      merk: 'SK-II',
      harga: 'Rp350.000',
      stok: 5,
    },
  ],
  columns: [
    { key: 'id', label: 'ID' },
    { key: 'nama_produk', label: 'nama produk' },
    { key: 'merk', label: 'merk' },
    { key: 'harga', label: 'harga' },
    { key: 'stok', label: 'stok' },
  ],
};
