export const riwayatTransaksi = {
  columns: [
    { key: 'id', label: 'ID' },
    { key: 'email', label: 'email' },
    { key: 'nama_produk', label: 'nama produk' },
    { key: 'merk', label: 'merk' },
    { key: 'jumlah', label: 'jumlah' },
  ],
  data: [
    {
      id: 1,
      email: 'rizka@gmail.com',
      nama_produk: 'cleanser',
      merk: 'SK-II',
      jumlah: 1,
    },
    {
      id: 2,
      email: 'rizka@gmail.com',
      nama_produk: 'cleanser',
      merk: 'SK-II',
      jumlah: 1,
    },
    {
      id: 3,
      email: 'rizka@gmail.com',
      nama_produk: 'cleanser',
      merk: 'SK-II',
      jumlah: 1,
    },
    {
      id: 4,
      email: 'rizka@gmail.com',
      nama_produk: 'cleanser',
      merk: 'SK-II',
      jumlah: 1,
    },
    {
      id: 5,
      email: 'rizka@gmail.com',
      nama_produk: 'cleanser',
      merk: 'SK-II',
      jumlah: 1,
    },
    {
      id: 6,
      email: 'rizka@gmail.com',
      nama_produk: 'cleanser',
      merk: 'SK-II',
      jumlah: 1,
    },
    {
      id: 7,
      email: 'rizka@gmail.com',
      nama_produk: 'cleanser',
      merk: 'SK-II',
      jumlah: 1,
    },
    {
      id: 8,
      email: 'rizka@gmail.com',
      nama_produk: 'cleanser',
      merk: 'SK-II',
      jumlah: 1,
    },
    {
      id: 9,
      email: 'rizka@gmail.com',
      nama_produk: 'cleanser',
      merk: 'SK-II',
      jumlah: 1,
    },
    {
      id: 10,
      email: 'rizka@gmail.com',
      nama_produk: 'cleanser',
      merk: 'SK-II',
      jumlah: 1,
    },
  ],
};
